version: '3.7'

services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
        networks:
            - my_network
    redis:
        image: redis
        networks:
            - my_network

networks:
    my_network:
